services:
  mysql:
    image: mysql:8.4
    container_name: ms-carrito-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-carrito_db}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p$${MYSQL_ROOT_PASSWORD:-root}"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - ticketti-network
  app:
    build: .
    container_name: app
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8082:8082"
    networks:
      - ticketti-network
    environment:
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/${MYSQL_DATABASE:-carrito_db}?createDatabaseIfNotExist=true"
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER:-root}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USER:-guest}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASS:-guest}
      SPRING_CONFIG_IMPORT: optional:configserver:http://host.docker.internal:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/

volumes:
  mysql_data:

networks:
  ticketti-network:
    external: true
