services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: carrito_db
    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - ticketti-network
  app:
    build: .
    container_name: app
    restart: on-failure
    depends_on:
      - mysql
    ports:
      - "8082:8082"
    networks:
      - ticketti-network
    environment:
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/carrito_db?createDatabaseIfNotExist=true"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

volumes:
  mysql_data:

networks:
  ticketti-network:
    external: true
